### ISSUE TITLE
Cannot install on Brackets 1.12

### ISSUE THREAD

**Issue by alecfehl** [soimon/brackets-document-outliner#5]
Incompatible. Can install on Brackets 1.11 but not 1.12.

**Comment by ferjesusjs8** [comment]
Well I'm using this web site meanwhile its not fixed yet
Link! >>>>>>
https://gsnedders.html5.org/outliner/

**Comment by soimon** [comment]
I have stopped using Brackets for a few years now, but for the love of open source there is an update available that fixes the compatibility issue with Brackets 1.12. Let me know if a problem still persists.

**Comment by alecfehl** [comment]
Yes - the recent updated fixed it and it now installs. Thank you!
